### ISSUE TITLE
Support for bot detection

### ISSUE THREAD

**Issue by Mte90** [rokcarl/slack-read-only-bot#1]
As we need to check if the user is a bot (and allow it) or specific users.

**Comment by rokcarl** [comment]
Can you add the user to the [list of admin users](https://github.com/rokcarl/slack-read-only-bot/blob/6c20eec/settings.yml.example#L6)?

If not, you can easily add support for this in the [`check_message`](https://github.com/rokcarl/slack-read-only-bot/blob/03a7e6c/bot.py#L40) method.

**Comment by Mte90** [comment]
Yes it isn't a problem the users but the bot.
We are doing some evaluations if still continue with our bot or switch to someone else that works. 
As example, we need just a channel where only bots can write and not the users.
